### ISSUE TITLE
Time setting fails / timezone is wrong

### ISSUE THREAD

**Issue by cierny** [MIT-STARLab/CLICK-A-RPi#20]
After testing Peter's timed command, which updates the time on the bus to the correct value, the payload time setting via time of tone fails as follows. The tai_secs value from python is printed below
```
Sep 12 08:25:52 click systemd[137]: Starting Set Time...
Sep 12 08:25:55 click python[2318]: 1615412659
Sep 12 08:25:55 click python[2318]: Traceback (most recent call last):
Sep 12 08:25:55 click python[2318]:   File "/root/bus/timeset.py", line 33, in <module>
Sep 12 08:25:55 click python[2318]:     set_time = time.gmtime(946684800+tai_secs)
Sep 12 08:25:55 click python[2318]: ValueError: timestamp out of range for platform time_t
Sep 12 08:25:55 click systemd[137]: set-time.service: Main process exited, code=exited, status=1/FAILURE
Sep 12 08:25:55 click systemd[137]: set-time.service: Failed with result 'exit-code'.
Sep 12 08:25:55 click systemd[137]: Failed to start Set Time.
```

**Comment by cierny** [comment]
It seems the tai_secs is actually TAI time since 1970 epoch. I updated set_time to tai_secs-37 in master and it seems to work okay.

**Comment by cierny** [comment]
Timezone is still set to EST, will have to fix with an updated golden image

**Comment by htomio** [comment]
> It seems the tai_secs is actually TAI time since 1970 epoch. I updated set_time to tai_secs-37 in master and it seems to work okay.

That's an issue in the ICD then? 

![Screen Shot 2021-03-10 at 17 11 17](https://user-images.githubusercontent.com/11082179/110704926-a7473680-81c3-11eb-99b0-0f2c18094f53.png)

**Comment by pgrenfell** [comment]
Tested sync command after Ondrej and Hannah's updates and everything is synced properly: PC, Bus, Payload.
