### ISSUE TITLE
Reduce Vociferousness of PAT Log File

### ISSUE THREAD

**Issue by pgrenfell** [MIT-STARLab/CLICK-A-RPi#26]
Save memory by eliminating redundant status messages, debug prints, etc. Also, delete old log files automatically.

**Comment by pgrenfell** [comment]
Added updates to streamline telemetry log.

**Comment by htomio** [comment]
vociferousness is a good word

**Comment by pgrenfell** [comment]
Haha, had to Google that one before using

Cheers,
Peter

**Comment by pgrenfell** [comment]
Tested on flat sat and pushed to master.
