### ISSUE TITLE
File delleted by file_manager.ManagedFileOpen is SYMLINK_MAX exceeded

### ISSUE THREAD

**Issue by PCSerra** [MIT-STARLab/CLICK-A-RPi#50]
If SYMLINK_MAX symbolic are present, ManagedFileOpen  will delete the file it created immediately.

Bug observed with python3, on the CLICK-BC FSW.

**Comment by PCSerra** [comment]
If you overwrite a file, the file manager will delete old version based on the index file name. The bug is only present if the file name is kept constant.  For A, this is ok, the solution should be always include timestamps in filename. For BC, large files can be generated, working on a solution using the file system.

**Comment by PCSerra** [comment]
Quick fix for BC, consider pasting to A:

                for i in range(0,file_count):
                    
                    current_name = file_data[i]['_name']
                    
                    if current_name == self.tags['_name']:
                        # File have been overwritten, one less file to track, no need to remove 
                        excess_file_count -= 1

                    elif(excess_file_count > 0):
                        # Another file, we still have too many, remove from index and delete 
                        os.remove(current_name) #clean up old files and stop indexing them
                        print('deleting %s' %  current_name)
                        excess_file_count -= 1

                    else:
                        # Diffrent file that we don't neet to remove
                        key_writer.writerow(file_data[i])

**Comment by pgrenfell** [comment]
Non-issue for CLICK A. Suggestion rejected.
