### ISSUE TITLE
Crash on PAT startup due to corruption in the /root/log/id_experiment.csv file

### ISSUE THREAD

**Issue by PCSerra** [MIT-STARLab/CLICK-A-RPi#7]
It seems that due to an unrelated issue in housekeeping/loadbalancer, the PAT process was restarted just as it was writing the experiment ID into the CSV file, and it wrote garbage instead of the correct number.

The line in /root/log/id_experiment.csv ended up being something like ^@^@^@ instead of 31 which was the current experiment ID – very strange.

In any case, every time PAT was started after this, it would crash on the std::stoi function trying to convert that garbage string into the previous experiment ID.

Ideally, we should handle this error correctly with a try/catch statement on the std::stoi function plus checking if the number is reasonable. If not, we should probably try recover the file – perhaps delete it and recover using the existing experiment folders.

**Comment by pgrenfell** [comment]
Resolved in branch issue7 and pushed to master.
