### ISSUE TITLE
PAT Mode Setting

### ISSUE THREAD

**Issue by pgrenfell** [MIT-STARLab/CLICK-A-RPi#9]
The pat is going into calibration when the "set pat mode" command for beacon align is being sent. This is likely due to the new multiple commandhandler architecture since the pat mode is currently being stored in a local variable in the commandhandler, and then a second command to execute the mode is needed "enter main loop". The way to fix this is to remove the local variable and execute immediately. Will also update the command sending language to reflect this updated behavior.

**Comment by pgrenfell** [comment]
Actually, reflecting more on this. The real issue is that the PAT mode needs to be stored in nonvolatile memory. This can be done by read/write to a csv file. Nothing in the commanding would need to change then. That's the best solution.

**Comment by pgrenfell** [comment]
Updated in issue9 branch and tested on flat sat.

**Comment by pgrenfell** [comment]
Merged with Master branch

**Comment by cierny** [comment]
Issue not resolved. Tested as follows:
- Start with beacon ON
- SET_MODE BEACON_ALIGN
- ENTER_PAT_MAIN
- SET_MODE DEFAULT
- EXIT_PAT_MAIN
- Turn beacon off
- Run TEST_PAT and follow instructions
- TEST_PAT enters OPEN_LOOP when GSE dithering is requested instead of CL tracking

**Comment by cierny** [comment]
Do I have to restart the PAT process after using BEACON_ALIGN to get into closed loop?

**Comment by cierny** [comment]
Worked OK after process restart
